a.out: main.o list.o queue.o linearqueue.o
	gcc -o a.out main.o list.o queue.o linearqueue.o

main.o: main.c
	gcc -c main.c

list.o: list.c
	gcc -c list.c

queue.o: queue.c
	gcc -c queue.c

linearqueue.o: linearqueue.c
	gcc -c linearqueue.c
